train:
  optimizer:
    type:               "adam"
    beta1:              0.9
    beta2:              0.999
    eps:                1e-8
  lr:                   2e-4
  lr_rampup_it:         1000
  scheduler_step_size:  10000
  batch:                4
  scheduler_gamma:      0.8
  save_model:           True
  save_interval:        10000
  resume:               False
  use_grad_clip:        True
  max_grad_norm:        1.0
  ema_rampup:           1000
  ema_rate:             0.999

dset:
  callable:             "datasets.tapehiss.TapeHissdset"
  path:                 "/scratch/elec/t412-asp/neural-tape-audio/Silence_AKAI_IPS[7.5]_MAXELL_SPLIT/Train"
  fs:                   44100
  seg_len:              65536
  num_workers:          2
  
model_dir:              "../weights/83"

network:
  checkpoint:           "../weights/83/noise-73000.pt"
  name:                 "unet_1d"
  callable:             "networks.unet_1d.UNet1D"
  Nin:                  1 # two would mean stereo
  depth:                8
  emb_dim:              32
  Ns:                   [8,16,16,16,16,16,16,16,16]
  Ss:                   [4,4,4,4,4,4,4,4,4]
  use_norm:             False

exp:
  exp_name:             "noise_diffusion"
  sample_rate:          44100 # sample rate where the generator works
  out_sample_rate:      44100 # sample rate at which we work
  seg_len:              65536

diff_params:
  T:                    16 # number of time steps
  sigma_data:           8e-4
  sigma_min:            5e-5
  sigma_max:            0.1
  ro:                   10
  Schurn:               0.25
  Snoise:               1.0000

outpainting:
  overlap:              0.2 # in seconds

hydra:
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep:         '='
        item_sep:       ','
        # Remove all paths, as the / in them would mess up things
        exclude_keys:   ['path_experiment',
          'hydra.job_logging.handles.file.filename']
